let pizzaJson = [
{id:1, 
        name:'Mussarela', img:'images/pizza.png', 
        sizes:[{size: '100g',
        price: 20.19,},{size: '530g',price: 30.19,},
        {size: '860g',price: 55.50} ],  
        description:'A Pizza de Mussarela é coberta com molho de tomate, queijo tipo mussarela, azeitonas pretas e orégano e massa com fermentação natural, oferece mais sabor e qualidade à sua mesa. Aproveite! '},
{id:2, name:'Calabresa', img:'images/pizza2.png',
        sizes:[{size: '100g',price: 20.19,},
        {size: '530g',price: 30.19,},
        {size: '860g',price: 55.50}],   
        description:'Pizza Calabresa – É especialmente preparada com recheio generoso de linguiça calabresa de primeira qualidade, queijo muçarela e orégano. A linguiça calabresa agrega um sabor único e levemente picante à pizza.'},
{id:3, name:'Quatro Queijos', img:'images/pizza3.png',
        sizes:[{size: '100g',price: 20.19,},
        { size: '530g', price: 30.19,},
        {size: '860g',price:55.50}],  
        description:'se você não é fã do forte gorgonzola, pode ficar tranquilo. A nossa pizza quatro queijos é feita com muçarela, catupiry, provolone e parmesão. Super saborosa e equilibrada.'},
{id:4, name:'Americana', img:'images/pizza4.png', 
        sizes:[{size: '100g',price: 20.19,},
        {size: '530g',price: 30.19,},
        {size: '860g',price: 55.50
}], 
        description:'Um verdadeiro clássico. Essa opção traz a combinação de sabores que todo mundo ama e se lembra imediatamente quando pensa em pizza, os ingredientes são: Molho de tomate, mussarela e presunto.'},
{id:5, name:'Sorvete', img:'images/pizza5.png', 
        sizes:[{size: '100g',price: 20.19,},
        {size: '530g',price: 30.19,},
        {size: '860g',price: 55.50}], 
        description:' Conhece nossa pizza de sorvete?! Uma massa bem fina, coberta de chocolate ao leite, pedaços generosos de morango e coberto com bolas de sorvete e castanhas de caju.'},
{id:6, name:'Moda da Casa', img:'images/pizza6.png', 
        sizes:[{size: '100g',price: 20.19,},
        {size: '530g',price: 30.19,},
        {size: '860g',price: 55.50}], 
        description:'Pizza a Moda da Casa com molho de tomate, presunto mussarela pimentão tomate cebola milho azeitona calabresa e orégano'},
{id:7, name:'Chocolate', img:'images/pizza7.png', 
        sizes:[{size: '100g',price: 20.19,},
        {size: '530g',price: 30.19,},
        {size: '860g',price: 55.50}], 
        description:'Já experimentou essa deliciosa  Pizza de Chocolate? A nossa pizza de chocolate é feita com muita Nutela e balas para decorar. É uma pizza muito saborosa e deliciosa.'},
];